# Generated by Django 4.0.5 on 2022-06-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='uploads')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='images', to='news.post')),
            ],
        ),
    ]
